[package]
name = "encryption-brute-forcer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.1"
signal-hook = "0.3.13"
aes-gcm = "0.9.4"