import type { Options as ExecaOptions } from '@commonjs/execa';
import execa from '@commonjs/execa';
import { Buffer } from 'node:buffer';

import type { BitwardenItemSubset } from '~p/types/bitwarden.js';
import { BitwardenItemType } from '~p/types/bitwarden.js';

import { debug } from './debug.js';

export interface BitwardenLoginSettings {
	email: string;
	masterPassword: string;
	clientId: string;
	clientSecret: string;
}

export async function saveEncryptedAdminPasswordToBitwarden({
	encryptedAdminPassword,
	bitwarden,
}: {
	encryptedAdminPassword: string;
	bitwarden: BitwardenLoginSettings;
}) {
	const bwEnv: Record<string, string> = {
		BW_PASSWORD: bitwarden.masterPassword,
	};

	const bwExec = (commandArgs: string[], options?: ExecaOptions) => {
		debug((f) => f`Running \`bw\` with args ${commandArgs}`);
		return execa('bw', commandArgs, {
			env: bwEnv,
			...options,
		});
	};

	debug(() => 'Logging out of Bitwarden...');
	await execa('bw', ['logout'], { reject: false });

	const { stdout: macosUser } = await execa('id', ['-un']);

	debug(() => 'Logging into Bitwarden...');
	await execa('bw', ['login', '--apikey'], {
		env: {
			BW_CLIENTID: bitwarden.clientId,
			BW_CLIENTSECRET: bitwarden.clientSecret,
		},
	});

	debug(() => 'Unlocking the vault...');
	const { stdout: bwSession } = await bwExec([
		'unlock',
		'--passwordenv',
		'BW_PASSWORD',
		'--raw',
	]);

	bwEnv.BW_SESSION = bwSession;

	debug(() => 'Searching for an existing AdminControl item...');
	const adminControlItemName =
		'Encrypted Admin Password Backup (created by AdminControl)';
	const { stdout: adminControlBwItemsJson } = await bwExec([
		'list',
		'items',
		'--search',
		adminControlItemName,
	]);

	const adminControlBwItems = JSON.parse(
		adminControlBwItemsJson
	) as BitwardenItemSubset[];

	if (adminControlBwItems.length === 0) {
		debug(
			() => 'An existing AdminControl item was not found, creating a new one...'
		);
		const { stdout: itemTemplateJson } = await bwExec([
			'get',
			'template',
			'item',
		]);

		const itemTemplate = JSON.parse(itemTemplateJson) as BitwardenItemSubset;

		itemTemplate.name = adminControlItemName;
		itemTemplate.login = {
			username: macosUser,
			password: encryptedAdminPassword,
		};
		itemTemplate.type = BitwardenItemType.login;
		itemTemplate.notes = 'Generated by AdminControl.';

		await bwExec([
			'create',
			'item',
			Buffer.from(JSON.stringify(itemTemplate)).toString('base64'),
		]);
	} else {
		debug(
			() =>
				'An existing AdminControl item was found, updating the existing one...'
		);
		const adminControlBwItemId = adminControlBwItems[0]?.id;

		if (adminControlBwItemId === undefined) {
			throw new Error('Bitwarden AdminControl item ID not found.');
		}

		const { stdout: adminControlBwItemJson } = await bwExec([
			'get',
			'item',
			adminControlBwItemId,
		]);

		const adminControlBwItem = JSON.parse(
			adminControlBwItemJson
		) as BitwardenItemSubset;

		adminControlBwItem.login.password = encryptedAdminPassword;

		await bwExec([
			'edit',
			'item',
			adminControlBwItemId,
			Buffer.from(JSON.stringify(adminControlBwItem)).toString('base64'),
		]);
	}

	debug(() => 'Logging out of Bitwarden...');
	await execa('bw', ['logout']);
}
