name: Release Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - packages/website/**
      - .github/workflows/github-pages.yaml

jobs:
  deploy:
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: ./packages/encryption/src/encryption-brute-forcer/target

      - name: Install dependencies
        run: pnpm run setup-monorepo && pnpm install

      - name: Compile Electron App for Release
        run: |
          pnpm compile:electron
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
